engine: amber
system: ala24
output_subdir: alaX/ala24_AMBER14_implicit_330K

input_pdb: pdbs/ala24.pdb
forcefield:
  - amber14-all.xml
  - implicit/gbn2.xml
ph: 7.0
implicit_solvent: true
salt_conc: 0.0
nonbonded_cutoff: 2.0

num_steps: 5000000        # 5,000,000 steps = 10 ns
output_freq: 1            # save every 1 steps = 2 fs → 5,000,000 frames
report_interval: 50000    # stdout log every 100 ps (logging only, not data)
temperature: 330
friction: 1.0
timestep: 0.002
integrator: langevin_middle

slurm:
  job_name: alaX-amber14-implicit-330K
  partition: a30
  gres: gpu:1
  time: 0-40:00:00
  mem: 20G
