# Chignolin, all-atom AMBER14 with GBn2 implicit solvent, 315 K.

engine: amber
system: cln
output_subdir: cln/AMBER14_implicit_stabilized_315K

input_pdb: pdbs/5AWL.pdb
forcefield:
  - amber14-all.xml
  - implicit/gbn2.xml
ph: 7.0
implicit_solvent: true
salt_conc: 0.0
nonbonded_cutoff: 2.0

num_steps: 50000000
output_freq: 1000
report_interval: 1000
temperature: 315
friction: 1.0
timestep: 0.002

slurm:
  job_name: cln-amber14-implicit-stabilized-315K
  partition: a30
  gres: gpu:1
  time: 0-40:00:00
  mem: 20G
